api_platform:
    title: Blizy API
    version: 1.0.0
    defaults:
        pagination_client_items_per_page: true
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']

    collection:
        pagination:
            items_per_page_parameter_name: itemsPerPage
