# php/config/api_platform/Category.yaml
App\Entity\Category:
  normalizationContext:
    groups: [ 'category' ]

  operations:
    ApiPlatform\Metadata\Get:
      filters:
        - 'category.search_filter'
        - 'category.order_filter'
    ApiPlatform\Metadata\GetCollection:
      filters:
        - 'category.search_filter'
        - 'category.order_filter'