# php/config/api_platform/Product.yaml
App\Entity\Product:
  normalizationContext:
    groups: ['product']

  operations:
    ApiPlatform\Metadata\Delete: ~
    ApiPlatform\Metadata\Get:
      filters:
        - 'product.search_filter'
        - 'product.range_filter'
    ApiPlatform\Metadata\GetCollection:
      filters:
        - 'product.search_filter'
        - 'product.order_filter'
        - 'product.numeric_filter'
