# php/config/serializer/Category.yaml
App\Entity\Category:
  attributes:
    id:
      groups: [ 'product', 'model', 'model:input' ]
    name:
      groups: [ 'model', 'product' ]
    brand:
      groups: [ 'model', 'product']

