# php/config/serializer/Model.yaml
App\Entity\Model:
  attributes:
    id:
      groups: ['model']
    name:
      groups: ['model', 'model:input']
    category:
      groups: ['model', 'model:input']
      openapi_context:
        example: '/api/categories/60'