# php/config/serializer/Model.yaml
App\Entity\Model:
  attributes:
    id:
      groups: ['model', 'product']
    name:
      groups: ['model', 'model:input', 'product']
    category:
      groups: ['model', 'model:input']