# php/config/services/filters.yaml
services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: false

  model.search_filter:
    parent: 'api_platform.doctrine.orm.search_filter'
    tags: [ 'api_platform.filter' ]
    arguments: [ { id: 'exact', name: 'ipartial' } ]

  model.order_filter:
    parent: 'api_platform.doctrine.orm.order_filter'
    tags: [ 'api_platform.filter' ]
    arguments: [ { name: ~ } ]
